name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      # OPTIONAL: if you committed public/data/team_81.json, this does nothing.
      # If you want CI to create it for you, uncomment and set your token:
      # - name: (Optional) Fetch Barca team data at build-time
      #   env:
      #     FD_TOKEN: ${{ secrets.FD_TOKEN }}
      #   run: |
      #     mkdir -p public/data
      #     curl -sS -H "X-Auth-Token: $FD_TOKEN" \
      #       "https://api.football-data.org/v4/teams/81" \
      #       -o public/data/team_81.json || true

      - name: Build site
        run: npm run build

      - name: SPA fallback + verify build
        run: |
          set -e
          cp build/index.html build/404.html
          test -f build/index.html || (echo "❌ build/index.html missing" && exit 1)
          echo "✅ build/index.html present"
          ls -la build | head -n 50

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
